spring.application.name=flashsale-engine
server.port=8090

# H2 Database configuration
spring.datasource.url=jdbc:h2:mem:flashsaledb 
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console :  enables a browser-based UI to view H2 database visually, like a mini database viewer
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console